name: Github pages deployer

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  gh-pages:
    # Name the Job
    name: Deploy to Github pages
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build 🔧
        run: cd tailwind && npx tailwindcss build tailwindStyles.css -c tailwind.config.prod.js | npx clean-css-cli > tailwind.css

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: . # The folder the action should deploy.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          PRESERVE: true
